title = "uniswap v2 sync&parse"
network = "ethereum"
factory = "0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f"
weth = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
#node_url = "https://aged-cosmological-snowflake.discover.quiknode.pro/edd8b6447abd44441d3112dc7cb3aa2b4540afb0/"
node_url = "https://indulgent-rough-feather.discover.quiknode.pro/30e19cc5162c0caa6c91678c457b0b166b09cc69/"
full_pair = false

start_block = 0
sync_interval = 7
sync_range = 400

reparse = false
parse_range = 500
parse_interval = 3

[mongo]
host = "localhost"
port = 5004
username = "root"
password = "password"

[redis]
host = "localhost"
port = 5005
password = "password"
db = 0
