title = "uniswap v2 sync&parse"

#区块网络
network = "ethereum"
#uniswap v2 factory地址
factory = "0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f"
#uniswap v2 weth 地址
weth = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"

node_url = "https://mainnet.infura.io/v3/44274c6033f54b7f9660c7cc2bd62018"

full_pair = false
skip_history = false
#default_pair_create_time = 1701888191

start_block = 0
sync_interval = 10

[mongo]
host = "localhost"
port = 5004
username = "root"
password = "password"

[redis]
host = "localhost"
port = 5005
password = "password"
db = 0
